name: fusion_ai
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2 
  firebase_auth: ^4.16.0 
  flutter_rating_bar: ^4.0.1
  file_picker: ^6.1.1 
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - images/logo.png

